all: SQLiteJDBC_connect.class SQLiteJDBC_createTable.class SQLiteJDBC_delete.class SQLiteJDBC_dropTables.class SQLiteJDBC_insert.class SQLiteJDBC_select.class SQLiteJDBC_update.class

SQLiteJDBC_connect.class: SQLiteJDBC_connect.java
	javac SQLiteJDBC_connect.java;

SQLiteJDBC_createTable.class: SQLiteJDBC_createTable.java
	javac SQLiteJDBC_createTable.java;

SQLiteJDBC_delete.class: SQLiteJDBC_delete.java
	javac SQLiteJDBC_delete.java;

SQLiteJDBC_dropTables.class: SQLiteJDBC_dropTables.java
	javac SQLiteJDBC_dropTables.java;

SQLiteJDBC_insert.class: SQLiteJDBC_insert.java
	javac SQLiteJDBC_insert.java;

SQLiteJDBC_select.class: SQLiteJDBC_select.java
	javac SQLiteJDBC_select.java;

SQLiteJDBC_update.class: SQLiteJDBC_update.java
	javac SQLiteJDBC_update.java;

clean:
	rm SQLiteJDBC_connect.class SQLiteJDBC_createTable.class SQLiteJDBC_delete.class SQLiteJDBC_dropTables.class SQLiteJDBC_insert.class SQLiteJDBC_select.class SQLiteJDBC_update.class;
	rm test.db;
